---
model_architecture: CondANFCoderTCM

model_params:
    num_filters: 64
    num_features: 96
    num_hyperpriors: 64
    hyper_filters: 64
    gdn_mode: standard
    in_channels: 3
    out_channels: 3
    kernel_size: 3
    num_layers: 2
    init_code: gaussian
    use_DQ: True
    share_wei: False
    use_code: False
    dec_add: False
    use_attn: False
    use_QE: False
    use_mean: True
    use_context: False
    condition: Gaussian
    quant_mode: RUN
    output_nought: True
    cond_coupling: True
    feat_filters: [64, 64, 64]
    in_channels_predprior: 64
    num_predprior_filters: 64
    num_cond_features: 64
    out_synthesis: 64
    gs_hidden: 64
    mc_decode_cond: False
