---
    model_architecture: FeatCondANFHyperPriorCoderPredPriorGS
        
    model_params:
        num_filters: 128
        num_features: 128
        num_hyperpriors: 128
        hyper_filters: 192
        gdn_mode: standard
        in_channels: 3
        out_channels: 3
        kernel_size: 5
        num_layers: 2
        init_code: gaussian
        use_DQ: True
        share_wei: False
        use_code: False
        dec_add: False
        use_attn: False
        use_QE: False
        use_mean: True
        use_context: False
        condition: Gaussian
        quant_mode: RUN
        output_nought: True
        cond_coupling: True
        num_cond_frames: 1
        in_channels_predprior: 3
        num_predprior_filters: 128
        num_cond_features : 64
        out_synthesis : 16
        gs_hidden : 64
        